apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vstsdockerbuild
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
          app: vstsdocerkbuild
    spec:
      containers:
      - image: paulgmiller/keepalive
        name: keepalive
        ports:
        - containerPort: 80
          protocol: TCP
      - image: docker:17
        name: docker
        ports:
        - containerPort: 4243
          protocol: TCP
      #todo mount a shared volume
          
